replicas: 2

appDeployment:
  labels:
    app: hospital
  name: hospital-container

image:
  repository: aryankollurishetty/hospital-app
  tag: v1.0.0

port: 80

appService:
  app: hospital
  type: NodePort
