replicaCount: 2

image:
  repository: aryankollurishetty/hospital-app
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080       # optional (only for NodePort)

labels:
  app: hospital

container:
  name: hospital-container
